name: github action ci cd

on:
  push:
    branches:
      - main
pull_request:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: read hellofile.txt
        run: echo "Hello Ostad. Welcome to ostad nama" > hellofile.txt 